name: Android CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      - name: Check project
        run: |
          echo "=== ROOT ==="
          ls -la
          echo "=== APP ==="
          ls -la app
          echo "=== SETTINGS ==="
          cat settings.gradle.kts
          echo "=== ROOT BUILD ==="
          cat build.gradle.kts
          echo "=== APP BUILD ==="
          cat app/build.gradle.kts

      - name: Check Android tasks
        run: gradle :app:tasks --all

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - name: Find APK
        run: find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Loki-debug-apk
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: error
